[features]
seeds = false
skip-lint = false
[programs.localnet]
hl_stake = "5vFwknUhxR12RMz6YD87v45KFvutSdRJoWBwcP8STs75"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "/home/bamdad/.config/solana/id.json"

# [programs.mainnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

# [programs.devnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

# [programs.testnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

# [programs.localnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"
